/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class WetterWerteGui extends javax.swing.JFrame
{

    /**
     * Creates new form WetterWerteGui
     */
    public WetterWerteGui()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        plMainDisplay = new javax.swing.JPanel();
        plInput = new javax.swing.JPanel();
        lbTemperature = new javax.swing.JLabel();
        slTemperature = new javax.swing.JSlider();
        blHumidity = new javax.swing.JLabel();
        slHumidity = new javax.swing.JSlider();
        btAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                onWA(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                onWinOpened(evt);
            }
        });

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        plMainDisplay.setLayout(new java.awt.GridLayout(1, 2));

        plInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Eingabe"));
        plInput.setLayout(new java.awt.GridLayout(6, 1));

        lbTemperature.setText("jLabel2");
        plInput.add(lbTemperature);

        slTemperature.setMaximum(40);
        slTemperature.setMinimum(-20);
        slTemperature.setPaintLabels(true);
        slTemperature.setPaintTicks(true);
        slTemperature.setToolTipText("1");
        slTemperature.setValue(10);
        plInput.add(slTemperature);

        blHumidity.setText("jLabel3");
        plInput.add(blHumidity);

        slHumidity.setPaintLabels(true);
        slHumidity.setPaintTicks(true);
        slHumidity.setToolTipText("");
        plInput.add(slHumidity);

        btAdd.setText("jButton1");
        plInput.add(btAdd);

        plMainDisplay.add(plInput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        plMainDisplay.add(jPanel1);

        getContentPane().add(plMainDisplay, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWA(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWA
    {//GEN-HEADEREND:event_onWA

    }//GEN-LAST:event_onWA

    private void onWinOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWinOpened
    {//GEN-HEADEREND:event_onWinOpened
        slTemperature.setMajorTickSpacing(10);
        slTemperature.setMinorTickSpacing(5);
        
        slHumidity.setMajorTickSpacing(20);
        slHumidity.setMinorTickSpacing(10);
    }//GEN-LAST:event_onWinOpened

    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(WetterWerteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(WetterWerteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(WetterWerteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(WetterWerteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new WetterWerteGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blHumidity;
    private javax.swing.JButton btAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTemperature;
    private javax.swing.JPanel plInput;
    private javax.swing.JPanel plMainDisplay;
    private javax.swing.JSlider slHumidity;
    private javax.swing.JSlider slTemperature;
    // End of variables declaration//GEN-END:variables
}
